#!/bin/bash
npm run lint --workspaces
if [ $? -ne 0 ]
then
    echo -e "\033[1mCode must be properly formatted before being committed\033[0m"
    echo ""
    exitcode=-1
fi

npm run test --workspaces
if [ $? -ne 0 ]
then
    echo -e "\033[1mTests must pass before being committed\033[0m"
    echo ""
    exitcode=-1
fi

HASCHANGES=$(git ls-files -m -o --exclude-standard)
if [ ! -z "$HASCHANGES" ]
then
    echo -e "\033[1mNo untracked files or unstaged changes before commit\033[0m"
    echo $HASCHANGES
    echo ""
    exitcode=-1
fi

exit $exitcode